version: '3'

services:
  api:
    build:
      context: ./backend
    container_name: api
    hostname: api
    ports:
        - "8000:8000"
    depends_on:
        - mongo
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    hostname: frontend
    ports:
      - "80:80"
    depends_on:
      - api
  mongo:
    container_name: mongo
    image:  mongo
    ports:
      - "27017:27017"