FROM node:21
WORKDIR /usr/src/app
COPY ./package*.json /usr/src/app
RUN npm install
RUN npm install -g pm2
COPY ./ /usr/src/app
EXPOSE 3000
# CMD ["node", "index.js"]
CMD ["pm2-runtime", "index.js", "-i", "4"]